// Builds an Excel workbook (.xlsx, as raw bytes) from the same
// InspectionRun-shaped object used by pdf.ts's buildInspectionPdf, so the
// Excel export mirrors the PDF report's content exactly (same sections,
// same field selection) — just in spreadsheet form. Used by the Inspection
// Manager "Export" action, which produces both a .pdf and a .xlsx for the
// same record.

import * as XLSX from "xlsx";
import { normalizeCapacity } from "../utils/capacity";

type AnyObj = Record<string, any>;

function fmt(v: unknown): string | number {
  if (v === null || v === undefined || v === "") return "-";
  if (typeof v === "number") return v;
  return String(v);
}

/** Mirrors pdf.ts's formatReportDate. */
function formatReportDate(d: Date): string {
  const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  const pad2 = (n: number) => String(n).padStart(2, "0");
  const time = `${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;
  return `${days[d.getDay()]} ${months[d.getMonth()]} ${d.getDate()} ${time} ${d.getFullYear()}`;
}

export function buildInspectionXlsx(run: AnyObj): Uint8Array {
  const inv = run.inventory || {};
  const sys = inv.system || {};
  const cpu = inv.cpu || {};
  const mem: AnyObj[] = inv.memory || [];
  const storage: AnyObj[] = inv.storage || [];
  const batt = inv.battery || {};
  const bios = inv.bios || {};
  const gpu: AnyObj[] = Array.isArray(inv.gpu) ? inv.gpu : inv.gpu ? [inv.gpu] : [];
  const disp = inv.display || {};
  const net = inv.network || {};
  const audio = inv.audio || {};
  const cam = inv.camera || {};
  const grading = run.grading || {};

  const totalMemGb = mem.reduce((s, m) => s + (m?.size_mb || 0), 0) / 1024;
  const memType = mem.find((m) => !m?.is_empty)?.memory_type;

  // ---- "Report" sheet: every label/value section, in the same reading
  // order as the PDF, with a bold-ish section-header row (2-column, second
  // cell blank) before each group's rows.
  const rows: (string | number)[][] = [];
  const section = (title: string) => rows.push([title, ""]);
  const pair = (label: string, value: unknown) => rows.push([label, fmt(value)]);

  section("Certificate Details");
  pair("Report Date", formatReportDate(new Date()));
  pair("Generated by", "Pulse Version 4.0 (64-bit)");

  section("System Information");
  pair("Manufacturer", sys.manufacturer);
  pair("Model", sys.model);
  pair("Serial Number", sys.serial_number);
  pair("System UUID", sys.uuid);
  pair("BIOS Version", sys.bios_version || bios.version);

  section("Event Information");
  pair("Date", run.timestamp);
  pair("CLY No", run.cly_no);
  pair("Inspector", run.inspector);
  pair("LOT", run.lot_name);
  pair("Inspection UUID", run.uuid);
  pair("Grade", run.grade ? `Grade ${run.grade}` : "-");

  if (grading.remarks) {
    section("Remarks");
    rows.push([String(grading.remarks), ""]);
  }

  section("Specifications: System");
  pair("Manufacturer", sys.manufacturer);
  pair("Model", sys.model);
  pair("Serial Number", sys.serial_number);
  pair("System UUID", sys.uuid);
  pair("Board Serial", sys.board_serial);
  pair("BIOS Version", sys.bios_version || bios.version);

  section("Specifications: Processor");
  pair("Processor", cpu.model);
  pair("Vendor", cpu.manufacturer);
  pair("Architecture", cpu.architecture);
  pair("Sockets", cpu.sockets);
  pair("Cores per Socket", cpu.cores_per_socket);
  pair("Threads", cpu.threads);
  pair("Max Speed", cpu.max_speed_mhz ? `${cpu.max_speed_mhz} MHz` : "-");
  pair("Min Speed", cpu.min_speed_mhz ? `${cpu.min_speed_mhz} MHz` : "-");
  pair("Current Speed", cpu.current_speed_mhz ? `${cpu.current_speed_mhz} MHz` : "-");
  pair("Cache L1", cpu.cache_l1);
  pair("Cache L2", cpu.cache_l2);
  pair("Cache L3", cpu.cache_l3);
  pair("Virtualization", cpu.virtualization != null ? (cpu.virtualization ? "Yes" : "No") : "-");
  pair("Hyper-Threading", cpu.hyper_threading != null ? (cpu.hyper_threading ? "Yes" : "No") : "-");

  section("Specifications: Memory");
  pair("Total Installed", mem.length ? `${totalMemGb.toFixed(1)} GB` : "-");
  pair("Type", memType);
  pair("Modules", mem.length || "-");
  mem.forEach((m, i) => {
    if (m?.is_empty) return;
    section(`Memory Module ${i + 1}`);
    pair("Slot", m.slot);
    pair("Bank Locator", m.bank_locator);
    pair("Size", m.size_mb != null ? `${(m.size_mb / 1024).toFixed(1)} GB` : "-");
    pair("Type", m.memory_type);
    pair("Manufacturer", m.manufacturer);
    pair("Serial", m.serial);
    pair("Part Number", m.part_number);
    pair("Speed", m.speed_mhz ? `${m.speed_mhz} MHz` : "-");
    pair("Onboard", m.is_onboard ? "Yes" : "No");
  });

  section("Specifications: Storage");
  pair("Drives", storage.length || "-");
  storage.forEach((d, i) => {
    section(storage.length > 1 ? `Storage Drive ${i + 1}` : "Storage Drive");
    pair("Device", d.device);
    pair("Slot", d.slot);
    pair("Model", d.model);
    pair("Serial", d.serial);
    pair("Firmware", d.firmware);
    pair("Transport", d.transport);
    pair("Type", d.storage_type);
    pair("Capacity", d.capacity_gb || (d.size_gb != null ? normalizeCapacity(d.size_gb) : "-"));
    pair("Health", d.health_percent != null ? `${d.health_percent}%` : "-");
    pair("Temperature", d.temperature_c != null ? `${d.temperature_c} °C` : "-");
    pair("Power-On Hours", d.power_on_hours);
    pair("Power Cycles", d.power_cycles);
    pair("Media Errors", d.media_errors);
    pair("Critical Warning", d.critical_warning);
  });

  section("Specifications: Motherboard");
  pair("BIOS Version", sys.bios_version || bios.version);
  pair("BIOS Vendor", bios.vendor);
  pair("BIOS Date", bios.release_date);
  pair("Board Serial", sys.board_serial);

  section("Specifications: Network");
  pair("WiFi Adapter", net.wifi);
  pair("WiFi", net.wifi_friendly);
  pair("WiFi MAC", net.wifi_mac);
  pair("Ethernet Adapter", net.ethernet);
  pair("Ethernet", net.ethernet_friendly);
  pair("Ethernet MAC", net.ethernet_mac);

  section("Specifications: Audio");
  pair("Codec", audio.codec);
  pair("Speakers", audio.speaker_type);
  pair("Mic", audio.mic_type);
  pair("Jack Type", audio.jack_type);

  section("Specifications: Battery");
  pair("Manufacturer", batt.manufacturer);
  pair("Model", batt.model);
  pair("Serial", batt.serial_number);
  pair("Technology", batt.technology);
  pair("Status", batt.status);
  pair("Cycle Count", batt.cycle_count);
  pair("Design Capacity", batt.design_capacity_mwh != null ? `${batt.design_capacity_mwh} mWh` : "-");
  pair("Full Charge Capacity", batt.full_charge_capacity_mwh != null ? `${batt.full_charge_capacity_mwh} mWh` : "-");
  pair("Current Capacity", batt.current_capacity_mwh != null ? `${batt.current_capacity_mwh} mWh` : "-");
  pair("Voltage", batt.voltage_mv != null ? `${batt.voltage_mv} mV` : "-");
  pair("Health", run.battery_health != null ? `${run.battery_health}%` : "-");

  section("Specifications: Bluetooth");
  pair("Bluetooth", net.bluetooth ? "Yes" : "No");

  section("Specifications: Display");
  pair("Manufacturer", disp.manufacturer);
  pair("Model", disp.model);
  pair("Panel Part Number", disp.panel_part_number);
  pair("Resolution", disp.resolution);
  pair("Size", disp.size_inches != null ? `${disp.size_inches}"` : "-");

  section("Specifications: Graphics");
  if (gpu.length) {
    gpu.forEach((g, i) => {
      if (gpu.length > 1) section(`GPU ${i + 1}`);
      pair("Vendor", g.vendor);
      pair("Model", g.model);
      pair("Bus Address", g.bus_address);
      pair("Driver", g.driver);
      pair("VRAM", g.vram);
      pair("Output Resolution", g.output_resolution);
    });
  } else {
    pair("GPU", "-");
  }

  section("Specifications: Webcam");
  pair("Vendor", cam.vendor);
  pair("Model", cam.model);
  pair("Device", cam.device);
  pair("Status", cam.status);

  const reportSheet = XLSX.utils.aoa_to_sheet([["Field", "Value"], ...rows]);
  reportSheet["!cols"] = [{ wch: 28 }, { wch: 50 }];

  // ---- "Test Results" sheet: same rows as pdf.ts's testResultsTable.
  const testRows: [string, unknown][] = [
    ["Speaker Test", run.speaker_test?.result],
    ["Webcam Test", run.webcam_test?.result],
    ["Keyboard Test", run.keyboard_test?.result],
    ["Touchpad Test", run.touchpad_test?.result],
    ["Battery Assessment", run.battery_assessment?.result],
    ["LCD Screen", grading.lcd_status],
    ["Top Cover", grading.top_cover_status],
    ["Bezel", grading.bezel_status],
    ["Palmrest", grading.palmrest_status],
    ["Bottom Cover", grading.bottom_cover_status],
    ["Keyboard (Cosmetic)", grading.keyboard_status],
    ["Touchpad (Cosmetic)", grading.touchpad_status],
  ];
  const testSheet = XLSX.utils.aoa_to_sheet([
    ["Test Name", "Result"],
    ...testRows.map(([name, result]) => [name, fmt(result || "PENDING")]),
  ]);
  testSheet["!cols"] = [{ wch: 28 }, { wch: 16 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, reportSheet, "Report");
  XLSX.utils.book_append_sheet(wb, testSheet, "Test Results");

  const out = XLSX.write(wb, { type: "array", bookType: "xlsx" });
  return new Uint8Array(out as ArrayBuffer);
}
